name: SecretCrush_build

on:
  push:
    branches: [master]

env:
  QT_VERSION: 6.7.2

jobs:
  build_win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install_qt
        run: |
          choco uninstall mingw
          choco install cmake
          pip install aqtinstall
          python3 -m aqt install-qt -O ${{ github.workspace }}/Qt/ windows desktop ${{ env.QT_VERSION }} win64_msvc2019_64 -m all
          echo "${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/msvc2019_64/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: build
        run: |
          mkdir build/
          cd build
          cmake ../ -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DQT_VERSION_MAJOR=6
          cmake --build . --config Release
          mkdir SecretCrush
          cp Release/SecretCrush.exe SecretCrush
          windeployqt SecretCrush/SecretCrush.exe --no-translations
          cp ../resources/images/icon.ico SecretCrush
          cp ../resources/images/SecretCrush.rc SecretCrush
          copy C:\Windows\System32\vccorlib140.dll SecretCrush\
          copy C:\Windows\System32\msvcp140.dll SecretCrush\
          copy C:\Windows\System32\vcruntime140.dll SecretCrush\
      - name: upload_artefact
        uses: actions/upload-artifact@v1
        with:
          name: SecretCrush
          path: build/SecretCrush

  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install_qt
        run: |
          pip install aqtinstall
          python3 -m aqt install-qt -O ${{ github.workspace }}/Qt/ mac desktop ${{ env.QT_VERSION }} -m all
          echo ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/macos/bin/ >> $GITHUB_PATH
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: upgrade
        run: |
          brew update -q -f
          brew upgrade -q -f
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
      - name: build
        run: |
          mkdir build
          cd build/
          cmake ../ -DCMAKE_BUILD_TYPE=Release -DQT_VERSION_MAJOR=6 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build . --config Release
          macdeployqt SecretCrush.app -always-overwrite
          wget https://raw.githubusercontent.com/arl/macdeployqtfix/master/macdeployqtfix.py
          ls -R SecretCrush.app
          hdiutil create -volname SecretCrush -srcfolder SecretCrush.app -ov -format UDZO SecretCrush.dmg
      - name: upload_artefact
        uses: actions/upload-artifact@v1
        with:
          name: SecretCrush.dmg
          path: ./build/SecretCrush.dmg
